packages: []

overrides:
  js-yaml: ^4.3.2
  undici: ^7.28.0

allowBuilds:
  electron: true
  ffmpeg-static: true
  "@memlab/cli": false
  electron-winstaller: false
  es5-ext: false
  memlab: false
  puppeteer: false
  sleep: false
